name: Lightninglogin
version: 1.0.0
description: "lightningstrike on login plugin."
Author: "WhiteGrits"

main: me.WhiteGrits.Lightninglogin.Main
database: false

commands:
  lightninglogin:
     description: This is the base command for lightninglogin.
     permission: lightninglogin.allowhelp
      
permissions:
   lightninglogin.*:
       description: Gives access to all lightninglogin commands
       children:
           lightninglogin.allow: true
           lightninglogin.allowtext: true
           lightninglogin.allowhelp: true
